install:
	$(info Changing .forward file name, use make clean to return to normal)
	mv .forward .forwardIGNORE
	python make_procmailrc.py

runCLI:
		cd CS419; make runCLI

clean:
	mv .forwardIGNORE .forward