def main():
	tray = []
	baton = ""
	base=2
	lucky=7
	exp=3
	nudge = base**exp*lucky
	tray.append(int(chr(nudge)) + 76)
	tray.append(int(chr(nudge)) + 96)
	tray.append(int(chr(nudge)) + 89)
	tray.append(int(chr(nudge)) + 102)
	tray.append(int(chr(nudge)) + 99)
	tray.append(int(chr(nudge)) + 107)
	tray.append(int(chr(nudge)) + 36)
	tray.append(int(chr(nudge)) + 24)
	tray.append(int(chr(nudge)) + 67)
	tray.append(int(chr(nudge)) + 93)
	tray.append(int(chr(nudge)) + 110)
	tray.append(int(chr(nudge)) + 97)
	tray.append(int(chr(nudge)) + 102)
	tray.append(int(chr(nudge)) + 38)
	tray.append(int(chr(nudge)) + 24)
	tray.append(int(chr(nudge)) + 63)
	tray.append(int(chr(nudge)) + 106)
	tray.append(int(chr(nudge)) + 103)
	tray.append(int(chr(nudge)) + 109)
	tray.append(int(chr(nudge)) + 104)
	tray.append(int(chr(nudge)) + 48)
	tray.append(int(chr(nudge)) + 24)
	tray.append(int(chr(nudge)) + 106)
	tray.append(int(chr(nudge)) + 103)
	tray.append(int(chr(nudge)) + 91)
	tray.append(int(chr(nudge)) + 99)
	tray.append(int(chr(nudge)) + 107)
	tray.append(int(chr(nudge)) + 25)
	tray.append(int(chr(nudge)) + 2)
	tray.append(int(chr(nudge)) + 37)
	tray.append(int(chr(nudge)) + 37)
	tray.append(int(chr(nudge)) + 75)
	tray.append(int(chr(nudge)) + 108)
	tray.append(int(chr(nudge)) + 89)
	tray.append(int(chr(nudge)) + 91)
	tray.append(int(chr(nudge)) + 113)
	tray.append(int(chr(nudge)) + 36)
	tray.append(int(chr(nudge)) + 24)
	tray.append(int(chr(nudge)) + 74)
	tray.append(int(chr(nudge)) + 97)
	tray.append(int(chr(nudge)) + 108)
	tray.append(int(chr(nudge)) + 108)
	tray.append(int(chr(nudge)) + 97)
	tray.append(int(chr(nudge)) + 93)
	tray.append(int(chr(nudge)) + 36)
	tray.append(int(chr(nudge)) + 24)
	tray.append(int(chr(nudge)) + 66)
	tray.append(int(chr(nudge)) + 93)
	tray.append(int(chr(nudge)) + 94)
	tray.append(int(chr(nudge)) + 94)
	tray.append(int(chr(nudge)) + 36)
	tray.append(int(chr(nudge)) + 24)
	tray.append(int(chr(nudge)) + 66)
	tray.append(int(chr(nudge)) + 89)
	tray.append(int(chr(nudge)) + 106)
	tray.append(int(chr(nudge)) + 93)
	tray.append(int(chr(nudge)) + 92)
	for x in range(len(tray)):
		baton += chr(tray[x])
	return baton

